import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { api } from "@/lib/api";

export default function OSJobPack() {
  const { jid } = useParams();
  const [j, setJ] = useState(null);
  const [photos, setPhotos] = useState([]);
  useEffect(() => {
    (async () => {
      const r = await api.get(`/jobs/${jid}/insurance-pack`); setJ(r.data);
      const p = await api.get(`/jobs/${jid}/photos`); setPhotos(p.data);
      setTimeout(() => window.print(), 800);
    })();
  }, [jid]);
  if (!j) return <div className="p-8">Loading...</div>;
  const ins = j.insurance || {};
  return (
    <div className="bg-white text-black min-h-screen p-10 print:p-0">
      <div className="flex items-center justify-between border-b-4 border-black pb-4">
        <div>
          <div className="text-3xl font-bold">WETAZZ · INSURANCE JOB PACK</div>
          <div className="text-sm">89 Maxwell St, Wellington NSW · hello@wetazz.com.au</div>
        </div>
        <div className="text-right"><div className="font-mono text-lg">{j.job_number}</div><div className="text-xs">{new Date().toLocaleDateString("en-AU")}</div></div>
      </div>
      <div className="grid grid-cols-2 gap-8 mt-6">
        <div><div className="text-xs uppercase font-bold mb-1">Insurer</div><div className="text-lg">{ins.insurer}</div>
          <div className="text-xs uppercase font-bold mt-3 mb-1">Claim #</div><div className="font-mono">{ins.claim_number}</div>
          <div className="text-xs uppercase font-bold mt-3 mb-1">Excess</div><div>A${(ins.excess||0).toFixed(2)}</div>
          <div className="text-xs uppercase font-bold mt-3 mb-1">Date of loss</div><div>{ins.date_of_loss || "—"}</div>
        </div>
        <div>
          <div className="text-xs uppercase font-bold mb-1">Assessor</div><div>{ins.assessor_name}</div>
          <div className="text-xs">{ins.assessor_phone} · {ins.assessor_email}</div>
          <div className="text-xs uppercase font-bold mt-3 mb-1">Customer</div><div>{j.customer?.first_name} {j.customer?.last_name}</div>
          <div className="text-xs">{j.customer?.email} · {j.customer?.phone}</div>
          <div className="text-xs uppercase font-bold mt-3 mb-1">Vehicle</div><div>{j.vehicle?.year} {j.vehicle?.make} {j.vehicle?.model}</div>
          <div className="text-xs font-mono">VIN {j.vehicle?.vin || "—"} · REGO {j.vehicle?.registration || "—"} · {j.vehicle?.colour}</div>
        </div>
      </div>
      {ins.notes && <div className="mt-6"><div className="text-xs uppercase font-bold mb-1">Notes</div><div className="text-sm">{ins.notes}</div></div>}
      {j.quotes?.length ? (
        <div className="mt-8"><div className="text-lg font-bold border-b pb-1 mb-3">Quotes</div>
          {j.quotes.map(q => (
            <div key={q.id} className="mb-4">
              <div className="flex justify-between"><div className="font-bold">{q.quote_number} · {q.status}</div><div className="font-mono">Total A${q.total?.toFixed(2)}</div></div>
              <table className="w-full text-sm mt-2"><thead><tr className="border-b"><th className="text-left py-1">Item</th><th className="text-right">Qty</th><th className="text-right">Unit</th><th className="text-right">Total</th></tr></thead>
                <tbody>{q.items?.map((it,i)=>(<tr key={i} className="border-b border-gray-200"><td className="py-1">{it.description}</td><td className="text-right">{it.quantity}</td><td className="text-right font-mono">A${it.unit_price?.toFixed(2)}</td><td className="text-right font-mono">A${it.total?.toFixed(2)}</td></tr>))}</tbody>
              </table>
            </div>
          ))}
        </div>
      ) : null}
      {photos.length ? (
        <div className="mt-8"><div className="text-lg font-bold border-b pb-1 mb-3">Damage photos</div>
          <div className="grid grid-cols-3 gap-2">{photos.slice(0,9).map(p => <img key={p.id} src={`data:image/jpeg;base64,${p.image_base64}`} className="w-full h-40 object-cover border" alt=""/>)}</div>
        </div>
      ) : null}
      <div className="mt-10 text-xs text-gray-500 border-t pt-2">Generated by WETAZZ OS · {new Date().toLocaleString("en-AU")}</div>
    </div>
  );
}
